### ISSUE TITLE
仕様書の内容についての質問

### ISSUE THREAD

**Issue by ewkobayashiyusuke** [ewest-github/RookieTraining2020#3]
仕様書の5ページ目の8.パス有無の入力についてで、ユーザーの判断に任せるというのは仕様書の7ページ目のパス画面(パスする)の項目の画像のような場合にどうするかをユーザーの判断に任せるという理解の仕方でよろしいのでしょうか。

**Comment by ew-yanagawa** [comment]
認識の通りで問題ありません。

**Comment by ewkobayashiyusuke** [comment]
承知いたしました、ありがとうございます。
