### ISSUE TITLE
仕様書のsetDirection()についての質問

### ISSUE THREAD

**Issue by ewkobayashiyusuke** [ewest-github/RookieTraining2020#4]
仕様書のsetDirection()について質問なのですが、この関数の役割は8方向に重みの数を設定するだけの役割を持つという解釈でよろしいのでしょうか。

**Comment by youichiinoue2** [comment]
はい、その解釈で合っています。

探索アルゴリズムについて、補足として
仕様書に「参考用プロジェクト」という章を追加したので、確認してください。
左方向に探索する参考コードが実行可能になっています。
そのプロジェクトは石の配置や方向を変更可能なので、挙動を見つつ、コードを確認してみてください。
探索アルゴリズムをどうコードにするかのイメージが掴めてくるかと思います。

**Comment by ewkobayashiyusuke** [comment]
おかげさまで探索アルゴリズムについて理解できました。ありがとうございました。
